### ISSUE TITLE
Crash when inserting TechReborn cells inside

### ISSUE THREAD

**Issue by nyuuns2** [vini2003/Shest#5] opened 2020-02-06 15:00 UTC
https://paste.ee/p/yBXAq
Reproduced by placing cells(preferrably filled) inside a shest. version is 1.2.3

**Comment by vini2003** [comment] 2020-02-08 15:48
nani

**Comment by vini2003** [comment] 2020-02-18 17:06
Duplicate of #2.

**Closed by vini2003** 2020-02-18 17:06 UTC
